included:
  - SiteCycle
  - SiteCycleTests

excluded:
  - SiteCycle/Preview Content

disabled_rules:
  - trailing_comma

opt_in_rules:
  - empty_count
  - closure_spacing
  - force_unwrapping
  - implicitly_unwrapped_optional

line_length:
  warning: 150
  error: 200

type_body_length:
  warning: 300
  error: 500

file_length:
  warning: 500
  error: 1000

function_body_length:
  warning: 50
  error: 100

identifier_name:
  min_length:
    warning: 2
    error: 1
  excluded:
    - id
    - i
